E2E Test for OMS
Adyen/adyen-salesforce-oms pull request #52
Opened 2024-08-23 11:09 UTC by shubhamk67

## Summary
Describe the changes proposed in this pull request:
- Added e2e tests for OMS

2024-08-23 13:38 UTC, dcardos requested changes
One minor change and some appointments.  Great work!

2024-08-23 13:38 UTC, dcardos commented on .github/workflows/e2e-tests.yml
> +    branches:
Would be nice to add a path, since we have some scripts now, we do not want to trigger them if no code was changed.

2024-08-23 13:38 UTC, dcardos commented on e2e/__tests__/creditCard.spec.mjs
> +    process.env.SALESFORCE_PASSWORD
I assume we cannot reuse that token to authenticate, right?

2024-08-23 13:38 UTC, dcardos commented on e2e/__tests__/creditCard.spec.mjs
> +    const fulfillmentOrderQueryResult = await sfConnection.query(
I don't see much problem on this in test, but could't we fetch the id from the response of the request above? Like you did for the invoice below. But I assume is because of the custom flow.

2024-08-23 14:02 UTC, zenit2001 requested changes

2024-08-23 14:04 UTC, shubhamk67 commented on e2e/__tests__/creditCard.spec.mjs
> +    process.env.SALESFORCE_PASSWORD
No, we can't use it with jsforce. The authUrl that we are using is specifically for sf cli.

2024-08-23 14:06 UTC, shubhamk67 commented on e2e/__tests__/creditCard.spec.mjs
> +    const fulfillmentOrderQueryResult = await sfConnection.query(
Yes, It's because of the custom flow. The flow response doesn't return the Id that's why I have to query it.

2024-08-23 14:15 UTC, shubhamk67 commented on .github/workflows/e2e-tests.yml
> +    branches:
done

2024-08-23 14:49 UTC, shubhamk67 commented on e2e/__tests__/creditCard.spec.mjs
> +  }, 90000);
It is currently set as 90 seconds

2024-08-23 15:03 UTC, dcardos submitted a review, later dismissed

2024-08-26 08:02 UTC, shanikantsingh submitted a review, later dismissed
jest is not needed for e2e tests.

2024-09-02 07:01 UTC, zenit2001 submitted a review, later dismissed

2024-09-03 12:10 UTC, zenit2001 approved these changes

2024-09-03 12:39 UTC, merged