feat: added lwc for confirmation screen on oobo flow
Adyen/adyen-salesforce-oms pull request #60
Opened 2024-10-03 15:14 UTC by shubhamk67

Added LWC for confirmation screen on OOBO flow to display Payment Link details.

2024-10-04 10:39 UTC, dcardos requested changes
Great LWC, very clean and well coded! I still prefer using lightning layout than the grid classes so it is more readable, but it is more of a personal preference.
Regarding the changes, only very minor stuff.
PS: I think later we will need to move all the texts to labels so we allow merchants to do theirs translations.  Me might also need to stop the flow from proceeding when in an error state.

2024-10-04 10:39 UTC, dcardos commented on force-app/main/default/lwc/adyenPblConfirmationScreen/adyenPblConfirmationScreen.html
> +                <div class="slds-align_absolute-center slds-m-around_medium">Your Order has been created and Card has been charged {currencyIsoCode} {amount}</div>
I believe it should be order with lower case "O" and card with lower case "C".

2024-10-04 10:39 UTC, dcardos commented on force-app/main/default/lwc/adyenPblConfirmationScreen/adyenPblConfirmationScreen.js-meta.xml
> +            <property name="shopperName" type="String" label="shopperName" />
I think you meant label as Shopper Name.

2024-10-04 13:18 UTC, dcardos requested changes

2024-10-04 13:18 UTC, dcardos commented on force-app/main/default/lwc/adyenPblConfirmationScreen/adyenPblConfirmationScreen.js-meta.xml
> +            <property name="shopperName" type="String" label="shopper Name" />
I think for consistency it should be Shopper with capital S, almost there. haha

2024-10-04 13:24 UTC, dcardos approved these changes

2024-10-07 07:05 UTC, zenit2001 approved these changes

2024-10-07 08:01 UTC, merged